GET http://localhost:3000

GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDMwNjI0MDcsImV4cCI6MTcwMzA2MzYwN30.N1fwFDLE857VOupmWMKCwWWdSO5hZ-0tw3EUscjhR53KiMZ3zwMrfnYEcIEaSt6KyhcJFg6Ur5AB2aw30Hjz5exrMyDuyfQK6GTYfCiinFdLSZEJH15hTKiqQs44ddBS267yIJ_YUw40-_-uQNBl7prnrF1LkDMWYkev3HHT3b2LnHWdKeGTYwRiym6RD5CYnQXuqBhskaHVZVcRKz4Kbg70z9U6z3k8vbuJQ8m8hLiBeaVpPnW569FOgrD8YKlfEXuvgpyuOaTusiuFaeXPkvc3kra58BfVTgpA4OS2PTBhvgE0wjO56rd2biw-n2CQco9bZKIIeyR312ZTEITjXQ